#import "@/graphql/fragments/Page.gql"

#import "@/graphql/fragments/Image.gql"
#import "@/graphql/fragments/Link.gql"
#import "@/graphql/fragments/Page.gql"

query GetPage($template: Page_template_Input) {
  Pages(where: { template: { equals: $template } }) {
    docs {
      ...Page
      homeFields {
        myTextField
      }
    }
  }
}
